image: docker:stable

stages:
  - build
  - push

build:
  stage: build
  script:
    - docker build -t rwbr/gitlab-ci-android:${CI_COMMIT_SHORT_SHA} .

push_latest:
  stage: push
  only:
    - master
  script:
    - docker tag rwbr/gitlab-ci-android:${CI_COMMIT_SHORT_SHA} rwbr/gitlab-ci-android:latest
    - docker push rwbr/gitlab-ci-android:latest

push_tag:
  stage: push
  only:
    - tags
  script:
    - docker tag rwbr/gitlab-ci-android:${CI_COMMIT_SHORT_SHA} rwbr/gitlab-ci-android:${CI_COMMIT_TAG}
    - docker push rwbr/gitlab-ci-android:${CI_COMMIT_TAG}
